Repository aquality-automation/aquality-selenium-dotnet, pull requests merged in 2019-12, with the labels that each got.

#153 Update version of Selenium.Core
  Aquality.Selenium/src/Aquality.Selenium/Aquality.Selenium.csproj
  Aquality.Selenium/src/Aquality.Selenium/Browsers/Browser.cs
  Aquality.Selenium/src/Aquality.Selenium/Browsers/BrowserManager.cs
  Aquality.Selenium/src/Aquality.Selenium/Browsers/BrowserNavigation.cs
  Aquality.Selenium/src/Aquality.Selenium/Elements/Actions/CheckBoxJsActions.cs
  Aquality.Selenium/src/Aquality.Selenium/Elements/Actions/ComboBoxJsActions.cs
  Aquality.Selenium/src/Aquality.Selenium/Elements/Actions/JsActions.cs
  Aquality.Selenium/src/Aquality.Selenium/Elements/Actions/MouseActions.cs
  Aquality.Selenium/src/Aquality.Selenium/Elements/CheckBox.cs
  Aquality.Selenium/src/Aquality.Selenium/Elements/ComboBox.cs
  Aquality.Selenium/src/Aquality.Selenium/Elements/Element.cs
  Aquality.Selenium/src/Aquality.Selenium/Elements/ElementFactory.cs
  Aquality.Selenium/src/Aquality.Selenium/Forms/Form.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Resources/settings.json
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Resources/settings.local.json
Labels: enhancement

#159 Bug/158 localization issue
  Aquality.Selenium/src/Aquality.Selenium/Browsers/BrowserStartup.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Unit/LocalizationManagerTests.cs
Labels: bug

#157 Feature/156 add properties to get registered services
  Aquality.Selenium/src/Aquality.Selenium/Aquality.Selenium.csproj
  Aquality.Selenium/src/Aquality.Selenium/Browsers/AqualityServices.cs
  Aquality.Selenium/src/Aquality.Selenium/Browsers/Browser.cs
  Aquality.Selenium/src/Aquality.Selenium/Browsers/BrowserFactory.cs
  Aquality.Selenium/src/Aquality.Selenium/Browsers/BrowserNavigation.cs
  Aquality.Selenium/src/Aquality.Selenium/Browsers/BrowserStartup.cs
  Aquality.Selenium/src/Aquality.Selenium/Browsers/LocalBrowserFactory.cs
  Aquality.Selenium/src/Aquality.Selenium/Browsers/RemoteBrowserFactory.cs
  Aquality.Selenium/src/Aquality.Selenium/Elements/Actions/JsActions.cs
  Aquality.Selenium/src/Aquality.Selenium/Elements/Actions/MouseActions.cs
  Aquality.Selenium/src/Aquality.Selenium/Elements/Element.cs
  Aquality.Selenium/src/Aquality.Selenium/Forms/Form.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/Actions/JsActionsTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/Actions/MouseActionsTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/AlertTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/BrowserTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/Elements/ComboBoxTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/Elements/LinkTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/Elements/TextBoxTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/HiddenElementsTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/TestApp/AutomationPractice/Forms/ProductListForm.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/TestApp/TheDemoSite/Forms/TheDemoSiteForm.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/TestApp/TheInternet/Forms/InfiniteScrollForm.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/TestApp/TheInternet/Forms/TheInternetForm.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/UITest.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/Usecases/BrowserConcurrencyTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/Usecases/CustomBrowserFactoryTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/Usecases/ElementExistsButNotDisplayedTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/Usecases/FileDownloadHelper.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/Usecases/FileDownloadingTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Integration/Usecases/ShoppingCartTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Unit/AqualityServicesTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Unit/BrowserManagerTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Unit/Configuration/CustomConfigurationTests.cs
  Aquality.Selenium/tests/Aquality.Selenium.Tests/Unit/LocalizationManagerTests.cs
Labels: feature
